apiVersion: v1
kind: Service
metadata:
  name: redis-follower
  labels:
    app: redis
    role: follower
    tier: backend
spec:
  ports:
  - port: 6379
  selector:
    app: redis
    {{ if .Values.replication }}
    role: follower
    {{ else }}
    role: leader
    {{ end }}
    tier: backend
